######################################################################
# Automatically generated by qmake (2.01a) lun. janv. 26 11:57:34 2009
######################################################################

TEMPLATE = app
TARGET = testparser 
DEPENDPATH += . ../
INCLUDEPATH += . ../
VERSION = 0.1
CONFIG += console

# Input
HEADERS += rawsubstream.h \
	   toyundasubstream.h \
	   testbase.h \
	   ../toyundasub.h

SOURCES += testrawtoyundaparser.cpp \
	   rawsubstream.cpp \
	   toyundasubstream.cpp \
	   ../toyundasub.cpp

