######################################################################
# Automatically generated by qmake (2.01a) jeu. mars 13 16:25:42 2008
######################################################################

TEMPLATE = app
TARGET = qtoyunda 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lxine
# Input
HEADERS += toystream.h toytype.h qxine.h qtoyosd.h
SOURCES += main.cpp toystream.cpp toytype.cpp qxine.cpp qtoyosd.cpp
